# Generated by Django 5.1 on 2024-09-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('informasi-teknologi', 'Informasi Teknologi'), ('marketing', 'Marketing'), ('bisnis', 'Bisnis')], max_length=30)),
                ('author', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('quota', models.PositiveIntegerField(null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
